#pragma checksum "..\..\ExampleRoutineGui.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C36EED91757AE5BB7FBCBEEABDBD208217ED90F746C81E12C582EA52B4AF7F13"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ExampleRoutine;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ExampleRoutine {
    
    
    /// <summary>
    /// ExampleRoutineGui
    /// </summary>
    public partial class ExampleRoutineGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 39 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SingleTargetMeleeSlotComboBox;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SingleTargetRangedSlotComboBox;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AoeMeleeSlotComboBox;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AoeRangedSlotComboBox;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FallbackSlotComboBox;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CombatRangeTextBox;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MaxMeleeRangeTextBox;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\ExampleRoutineGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MaxRangeRangeTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ExampleRoutine;component/exampleroutinegui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\ExampleRoutineGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SingleTargetMeleeSlotComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 2:
            this.SingleTargetRangedSlotComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.AoeMeleeSlotComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.AoeRangedSlotComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.FallbackSlotComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.CombatRangeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.MaxMeleeRangeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.MaxRangeRangeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

